export const ROUTES = {
  AGENT_SKILLS_INDEX: "/.well-known/agent-skills/index.json",
  AGENT_SKILLS_TERMUI_SKILL: "/.well-known/agent-skills/termui-skill.md",
  API_CATALOG: "/.well-known/api-catalog",
  API_STATUS: "/api/status",
  LEGACY_COMPONENTS: "/components",
  WIDGETS: "/widgets",
  DOCS: "/docs",
  DOCS_CHANGELOG: "/docs/changelog",
  DOCS_CHARTS: "/docs/charts",
  DOCS_COMPONENTS_LEGACY: "/docs/components",
  DOCS_WIDGETS: "/docs/widgets",
  DOCS_INSTALLATION: "/docs/installation",
  DOCS_TEMPLATES: "/docs/templates",
  DOCS_THEMES: "/docs/themes",
  DOCS_THEMING: "/docs/theming",
  CHARTS: "/charts",
  HOME: "/",
  LAUNCH_WEEK: "/launch-week",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  LLMS_MD: "/llms.md",
  LLMS_MDX: "/llms.mdx",
  OPENAPI: "/openapi.json",
  RSS: "/rss.xml",
} as const;
